apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  project: homelab
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.3
  syncPolicy:
    automated:
      prune: true
