apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  project: homelab
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.3
    helm:
      values: |-
        helmPreUpgradeCheckerJob:
          enabled: false
  syncPolicy:
    automated:
      prune: true
