apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: homelab
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.0.0
    helm:
      values: |-
        grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            path: /
            hosts:
            - grafana.hongphucvu.com
          grafana.ini:
            server:
              root_url: https://grafana.hongphucvu.com
            auth.azuread:
              name: Azure AD
              enabled: true
              allow_sign_up: true
              auto_login: false
              client_id: $__file{/etc/secrets/grafana-secret/client_id}
              client_secret: $__file{/etc/secrets/grafana-secret/client_secret}
              scopes: openid email profile
              auth_url: https://login.microsoftonline.com/2a113a85-e93a-402e-af34-4ab699ed1f7c/oauth2/v2.0/authorize
              token_url: https://login.microsoftonline.com/2a113a85-e93a-402e-af34-4ab699ed1f7c/oauth2/v2.0/token
              allowed_organizations: 2a113a85-e93a-402e-af34-4ab699ed1f7c
              role_attribute_strict: false
              allow_assign_grafana_admin: true
              skip_org_role_sync: false
              use_pkce: true
          extraSecretMounts: 
          - name: grafana-secret
            secretName: grafana-secret
            defaultMode: 0440
            mountPath: /etc/secrets/grafana-secret
            readOnly: true
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true